import pymysql
import pandas as pd
from tabulate import tabulate
import warnings
warnings.filterwarnings('ignore')
conn= pymysql.connect(user = 'root',
                              host = 'localhost',
                              passwd='123',    
                              database = 'sales_analysis',
                              charset='utf8')
cursor=conn.cursor()
def update_1():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set model ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(e,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_2():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set area ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,e,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_3():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set year ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,e)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_4():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set january ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_5():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set february ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_6():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set march ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_7():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set april ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_8():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set may ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")

def update_9():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set june ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_10():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set july ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_11():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set august ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_12():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set september ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_13():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set octuber ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_14():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set november ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")
def update_15():
    a=input("ENTER MODEL")
    b=input("ENTER AREA")
    c=int(input("ENTER YEAR"))
    e=input("ENTER NEW VALUE")
    q="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
    df=pd.read_sql(q,conn)
    cursor.execute(q)
    if cursor.fetchone:
        cursor.execute("update sales_report set december ='{}' where AREA= '{}' and year={} and Model='{}';".format(e,b,c,a))
        conn.commit()
        print("ROW UPDATED")
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
        z="select*from sales_report where model='{}' and area='{}' and year={};".format(a,b,c)
        df=pd.read_sql(z,conn)
        print(tabulate(df,headers="keys",tablefmt="psql",showindex=False))
    else:
        print("WRONG DATA")        
